#include "axiom/qwen4exp/ple.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <limits>
#include <utility>
#include <vector>

namespace {

using axiom::qwen4exp::kPleConvHistory;
using axiom::qwen4exp::kPleConvKernelSize;
using axiom::qwen4exp::kPleHeadCount;
using axiom::qwen4exp::kPleNgramOrder;
using axiom::qwen4exp::ple_head_ids;
using axiom::qwen4exp::ple_metadata;
using axiom::qwen4exp::ple_session_state;
using axiom::qwen4exp::ple_status;
using axiom::qwen4exp::ple_status_code;

constexpr std::int64_t kVocabSize = 248320;
constexpr std::int64_t kEos = 248044;
constexpr std::uint64_t kSeed = 1234u;

/* Values read from the three I64 metadata tensors in the pinned RadixArk
 * checkpoint.  They are intentionally hardcoded rather than generated by the
 * implementation under test. */
constexpr std::array<std::int64_t, kPleNgramOrder> kGoldenMultipliers{
        23703573157769ll,
        20109073645365ll,
        8052911324071ll,
};

constexpr std::array<std::int64_t, kPleHeadCount> kGoldenOffsets{
        0ll,
        20000003ll,
        40000026ll,
        60000059ll,
        80000106ll,
        100000165ll,
        120000228ll,
        140000297ll,
        160000374ll,
        180000455ll,
        200000548ll,
        220000655ll,
        240000802ll,
        260000955ll,
        280001114ll,
        300001275ll,
};

constexpr std::array<std::int64_t, kPleHeadCount> kGoldenVocabSizes{
        20000003ll,
        20000023ll,
        20000033ll,
        20000047ll,
        20000059ll,
        20000063ll,
        20000069ll,
        20000077ll,
        20000081ll,
        20000093ll,
        20000107ll,
        20000147ll,
        20000153ll,
        20000159ll,
        20000161ll,
        20000171ll,
};

constexpr ple_head_ids kGoldenFresh101{
        14526383ll,
        36975477ll,
        51939184ll,
        65076202ll,
        94510971ll,
        111786935ll,
        138448715ll,
        155393638ll,
        167579692ll,
        181767276ll,
        211184823ll,
        226303266ll,
        246271192ll,
        267465224ll,
        281469089ll,
        313531602ll,
};

constexpr ple_head_ids kGoldenContext101102Token103{
        13973293ll,
        38982688ll,
        41490734ll,
        69005804ll,
        84022205ll,
        109028451ll,
        126538435ll,
        156553034ll,
        168213666ll,
        188586465ll,
        202358030ll,
        230296566ll,
        250490002ll,
        270684104ll,
        284082339ll,
        311074302ll,
};

constexpr ple_head_ids kGoldenFresh201{
        7322707ll,
        22176128ll,
        43340350ll,
        65156241ll,
        82028269ll,
        101782983ll,
        132162558ll,
        154063925ll,
        170727983ll,
        187175610ll,
        215898555ll,
        231901619ll,
        243003708ll,
        275332458ll,
        286381266ll,
        303669154ll,
};

bool expect(bool condition, const char *message) {
    if (condition) return true;
    std::fprintf(stderr, "qwen4exp-ple-test: %s\n", message);
    return false;
}

bool expect_ok(ple_status status, const char *message) {
    if (status.ok()) return true;
    std::fprintf(stderr, "qwen4exp-ple-test: %s: %s\n",
                 message, status.message);
    return false;
}

bool expect_code(ple_status status,
                 ple_status_code code,
                 const char *message) {
    if (status.code == code) return true;
    std::fprintf(stderr,
                 "qwen4exp-ple-test: %s: expected status %u, got %u (%s)\n",
                 message,
                 static_cast<unsigned>(code),
                 static_cast<unsigned>(status.code),
                 status.message);
    return false;
}

ple_metadata golden_metadata() {
    ple_metadata metadata;
    metadata.unigram_vocab_size = kVocabSize;
    metadata.eos_token_id = kEos;
    metadata.layer_multipliers = kGoldenMultipliers;
    metadata.ngram_heads_offsets = kGoldenOffsets;
    metadata.ngram_heads_vocab_sizes = kGoldenVocabSizes;
    return metadata;
}

/* Independent scalar reference.  Unlike the implementation, it retains the
 * complete token stream and searches for the previous EOS at each position,
 * directly mirroring the segment_start definition in Transformers. */
ple_head_ids reference_next_ids(const ple_metadata &metadata,
                                std::vector<std::int64_t> *history,
                                std::int64_t token) {
    const std::size_t position = history->size();
    std::size_t segment_start = 0u;
    for (std::size_t index = 0; index < position; ++index) {
        if ((*history)[index] == metadata.eos_token_id) {
            segment_start = index + 1u;
        }
    }

    std::array<std::int64_t, kPleNgramOrder> shifted{};
    shifted[0] = token;
    for (std::size_t shift = 1; shift < kPleNgramOrder; ++shift) {
        shifted[shift] =
                position >= shift && position - shift >= segment_start
                        ? (*history)[position - shift]
                        : metadata.eos_token_id;
    }

    const std::uint64_t first =
            static_cast<std::uint64_t>(shifted[0]) *
            static_cast<std::uint64_t>(metadata.layer_multipliers[0]);
    const std::uint64_t second =
            static_cast<std::uint64_t>(shifted[1]) *
            static_cast<std::uint64_t>(metadata.layer_multipliers[1]);
    const std::uint64_t third =
            static_cast<std::uint64_t>(shifted[2]) *
            static_cast<std::uint64_t>(metadata.layer_multipliers[2]);
    const std::uint64_t bigram = first ^ second;
    const std::uint64_t trigram = bigram ^ third;

    ple_head_ids ids{};
    for (std::size_t head = 0; head < kPleHeadCount; ++head) {
        const std::uint64_t mixed = head < 8u ? bigram : trigram;
        ids[head] = metadata.ngram_heads_offsets[head] +
                static_cast<std::int64_t>(
                        mixed % static_cast<std::uint64_t>(
                                        metadata.ngram_heads_vocab_sizes[head]));
    }
    history->push_back(token);
    return ids;
}

std::vector<float> reference_conv_window(
        const std::vector<std::vector<float>> &history,
        const std::vector<float> &current) {
    std::vector<float> window(kPleConvKernelSize * current.size(), 0.0f);
    constexpr std::array<std::size_t, 3> distances{9u, 6u, 3u};
    for (std::size_t tap = 0; tap < distances.size(); ++tap) {
        if (history.size() < distances[tap]) continue;
        const auto &source = history[history.size() - distances[tap]];
        std::copy(source.begin(), source.end(),
                  window.begin() + static_cast<std::ptrdiff_t>(
                                           tap * current.size()));
    }
    std::copy(current.begin(), current.end(),
              window.begin() + static_cast<std::ptrdiff_t>(
                                       3u * current.size()));
    return window;
}

bool test_checkpoint_golden_metadata() {
    bool ok = true;
    std::array<std::int64_t, kPleNgramOrder> multipliers{};
    ok = ok && expect_ok(
            axiom::qwen4exp::ple_derive_layer_multipliers(
                    kVocabSize, 0u, kSeed, &multipliers),
            "could not derive layer multipliers");
    ok = ok && expect(multipliers == kGoldenMultipliers,
                      "derived multipliers differ from checkpoint golden");

    std::array<std::int64_t, kPleHeadCount> offsets{};
    std::array<std::int64_t, kPleHeadCount> vocab_sizes{};
    ok = ok && expect_ok(
            axiom::qwen4exp::ple_derive_head_layout(
                    20000000ll, 0u, &offsets, &vocab_sizes),
            "could not derive head layout");
    ok = ok && expect(offsets == kGoldenOffsets,
                      "derived offsets differ from checkpoint golden");
    ok = ok && expect(vocab_sizes == kGoldenVocabSizes,
                      "derived vocab sizes differ from checkpoint golden");

    const ple_metadata metadata = golden_metadata();
    ok = ok && expect_ok(
            axiom::qwen4exp::ple_validate_metadata(metadata),
            "checkpoint metadata was rejected");

    ple_head_ids ids{};
    ok = ok && expect_ok(
            axiom::qwen4exp::ple_compute_head_ids(
                    metadata, {kEos, kEos}, 101, &ids),
            "fresh token 101 hashing failed");
    ok = ok && expect(ids == kGoldenFresh101,
                      "fresh token 101 differs from hardcoded golden");

    ok = ok && expect_ok(
            axiom::qwen4exp::ple_compute_head_ids(
                    metadata, {101, 102}, 103, &ids),
            "context token 103 hashing failed");
    ok = ok && expect(ids == kGoldenContext101102Token103,
                      "context token 103 differs from hardcoded golden");

    ok = ok && expect_ok(
            axiom::qwen4exp::ple_compute_head_ids(
                    metadata, {103, kEos}, 201, &ids),
            "post-EOS token 201 hashing failed");
    ok = ok && expect(ids == kGoldenFresh201,
                      "post-EOS token retained pre-EOS context");
    ok = ok && expect_ok(
            axiom::qwen4exp::ple_compute_head_ids(
                    metadata, {kEos, kEos}, 201, &ids),
            "fresh token 201 hashing failed");
    ok = ok && expect(ids == kGoldenFresh201,
                      "fresh token 201 differs from hardcoded golden");
    return ok;
}

bool test_transactional_ids_eos_and_conv() {
    constexpr std::size_t kChannels = 2u;
    const ple_metadata metadata = golden_metadata();
    ple_session_state state;
    bool ok = expect_ok(state.configure(metadata, kChannels, 16u),
                        "session configure failed");
    ok = ok && expect(state.conv_window_elements() == 8u,
                      "conv window geometry is not four taps");
    ok = ok && expect_ok(state.begin_transaction(),
                         "transaction begin failed");

    const std::vector<std::int64_t> tokens{
            101, 102, 103, kEos, 201, 202, 203, 204, 205, 206};
    std::vector<std::int64_t> reference_tokens;
    std::vector<std::vector<float>> reference_frames;
    for (std::size_t index = 0; index < tokens.size(); ++index) {
        const ple_head_ids expected_ids =
                reference_next_ids(metadata, &reference_tokens, tokens[index]);
        ple_head_ids actual_ids{};
        ok = ok && expect_ok(state.stage_token(tokens[index], &actual_ids),
                             "transaction token stage failed");
        ok = ok && expect(actual_ids == expected_ids,
                          "session hash differs from independent EOS reference");

        const std::vector<float> frame{
                static_cast<float>(index + 1u),
                static_cast<float>(101u + index)};
        const std::vector<float> expected_window =
                reference_conv_window(reference_frames, frame);
        std::array<float, kPleConvKernelSize * kChannels> actual_window{};
        ok = ok && expect_ok(
                state.stage_conv_frame(frame.data(), frame.size(),
                                       actual_window.data(), actual_window.size()),
                "transaction conv stage failed");
        ok = ok && expect(std::equal(actual_window.begin(), actual_window.end(),
                                     expected_window.begin()),
                          "dilated conv window differs from independent reference");
        reference_frames.push_back(frame);
    }

    /* Publish seven steps and reject three.  Both token and convolution state
     * must stop exactly at the accepted prefix. */
    ok = ok && expect_ok(state.commit_prefix(7u),
                         "prefix commit failed");
    ok = ok && expect(state.committed_tokens() == 7u,
                      "prefix commit published the wrong token count");
    ok = ok && expect(state.committed_context() ==
                              std::array<std::int64_t, 2>{202, 203},
                      "prefix commit retained rejected token context");
    ok = ok && expect(state.committed_conv_frames() == 7u,
                      "prefix commit retained rejected conv frames");

    reference_tokens.resize(7u);
    reference_frames.resize(7u);
    const ple_head_ids expected_after_prefix =
            reference_next_ids(metadata, &reference_tokens, 777);
    const std::vector<float> candidate_frame{77.0f, 177.0f};
    const std::vector<float> expected_after_prefix_window =
            reference_conv_window(reference_frames, candidate_frame);

    ple_head_ids first_ids{};
    std::array<float, kPleConvKernelSize * kChannels> first_window{};
    ok = ok && expect_ok(state.begin_transaction(),
                         "rollback transaction begin failed");
    ok = ok && expect_ok(state.stage_token(777, &first_ids),
                         "rollback candidate token stage failed");
    ok = ok && expect(first_ids == expected_after_prefix,
                      "candidate saw rejected token context");
    ok = ok && expect_ok(
            state.stage_conv_frame(candidate_frame.data(), candidate_frame.size(),
                                   first_window.data(), first_window.size()),
            "rollback candidate conv stage failed");
    ok = ok && expect(std::equal(first_window.begin(), first_window.end(),
                                 expected_after_prefix_window.begin()),
                      "candidate saw rejected conv frames");
    ok = ok && expect_ok(state.rollback(), "transaction rollback failed");
    ok = ok && expect(state.committed_tokens() == 7u,
                      "rollback changed committed token count");

    ple_head_ids second_ids{};
    std::array<float, kPleConvKernelSize * kChannels> second_window{};
    ok = ok && expect_ok(state.begin_transaction(),
                         "repeat transaction begin failed");
    ok = ok && expect_ok(state.stage_token(777, &second_ids),
                         "repeat candidate token stage failed");
    ok = ok && expect_ok(
            state.stage_conv_frame(candidate_frame.data(), candidate_frame.size(),
                                   second_window.data(), second_window.size()),
            "repeat candidate conv stage failed");
    ok = ok && expect(first_ids == second_ids && first_window == second_window,
                      "rollback was not bitwise state-preserving");
    ok = ok && expect_ok(state.commit_prefix(1u),
                         "single-token commit failed");

    std::array<float, kPleConvHistory * kChannels> committed_history{};
    ok = ok && expect_ok(
            state.copy_committed_conv_history(
                    committed_history.data(), committed_history.size()),
            "committed conv history copy failed");
    std::array<float, kPleConvHistory * kChannels> expected_history{
            0.0f, 0.0f,
            1.0f, 101.0f,
            2.0f, 102.0f,
            3.0f, 103.0f,
            4.0f, 104.0f,
            5.0f, 105.0f,
            6.0f, 106.0f,
            7.0f, 107.0f,
            77.0f, 177.0f,
    };
    ok = ok && expect(committed_history == expected_history,
                      "committed conv ring is not chronological/right-padded");
    ok = ok && expect(state.committed_context() ==
                              std::array<std::int64_t, 2>{203, 777},
                      "single-token commit produced wrong token context");
    return ok;
}

bool test_fail_closed_contract() {
    bool ok = true;
    ple_metadata bad = golden_metadata();
    bad.ngram_heads_offsets[1] += 1;
    ok = ok && expect_code(
            axiom::qwen4exp::ple_validate_metadata(bad),
            ple_status_code::invalid_metadata,
            "non-contiguous offsets were admitted");
    bad = golden_metadata();
    bad.layer_multipliers[0] += 1;
    ok = ok && expect_code(
            axiom::qwen4exp::ple_validate_metadata(bad),
            ple_status_code::invalid_metadata,
            "even multiplier was admitted");
    bad = golden_metadata();
    bad.ngram_heads_vocab_sizes[4] += 1;
    ok = ok && expect_code(
            axiom::qwen4exp::ple_validate_metadata(bad),
            ple_status_code::invalid_metadata,
            "non-prime head vocabulary was admitted");

    ple_session_state state;
    ple_head_ids ids{};
    ok = ok && expect_code(state.begin_transaction(),
                           ple_status_code::invalid_state,
                           "unconfigured transaction was admitted");
    ok = ok && expect_ok(state.configure(golden_metadata(), 2u, 2u),
                         "fail-closed fixture configure failed");
    ok = ok && expect_code(state.stage_token(1, &ids),
                           ple_status_code::invalid_state,
                           "token without transaction was admitted");
    ok = ok && expect_ok(state.begin_transaction(),
                         "fail-closed transaction begin failed");
    ok = ok && expect_code(state.begin_transaction(),
                           ple_status_code::invalid_state,
                           "nested transaction was admitted");
    ok = ok && expect_code(state.stage_token(kVocabSize, &ids),
                           ple_status_code::out_of_range,
                           "out-of-vocabulary token was admitted");
    ok = ok && expect_ok(state.stage_token(11, &ids),
                         "valid token stage failed");
    ok = ok && expect_code(state.stage_token(12, &ids),
                           ple_status_code::invalid_state,
                           "second token bypassed its pending conv frame");

    const std::array<float, 2> frame{1.0f, 2.0f};
    std::array<float, 8> window{};
    ok = ok && expect_code(
            state.stage_conv_frame(frame.data(), 1u,
                                   window.data(), window.size()),
            ple_status_code::invalid_argument,
            "wrong conv frame size was admitted");
    const std::array<float, 2> non_finite{
            1.0f, std::numeric_limits<float>::quiet_NaN()};
    ok = ok && expect_code(
            state.stage_conv_frame(non_finite.data(), non_finite.size(),
                                   window.data(), window.size()),
            ple_status_code::invalid_argument,
            "non-finite conv frame was admitted");
    ok = ok && expect_code(state.commit_prefix(1u),
                           ple_status_code::invalid_state,
                           "incomplete token/conv pair was committed");
    ok = ok && expect_ok(
            state.stage_conv_frame(frame.data(), frame.size(),
                                   window.data(), window.size()),
            "valid conv frame stage failed");
    ok = ok && expect_code(state.commit_prefix(2u),
                           ple_status_code::out_of_range,
                           "oversized accepted prefix was committed");
    ok = ok && expect_ok(state.rollback(),
                         "fail-closed transaction rollback failed");
    ok = ok && expect(state.committed_tokens() == 0u,
                      "failed operations changed committed state");
    ok = ok && expect_code(state.rollback(),
                           ple_status_code::invalid_state,
                           "rollback without transaction was admitted");
    return ok;
}

bool test_committed_ring_wrap_and_move() {
    constexpr std::size_t kChannels = 1u;
    const ple_metadata metadata = golden_metadata();
    ple_session_state state;
    bool ok = expect_ok(state.configure(metadata, kChannels, 1u),
                        "ring fixture configure failed");
    std::vector<std::int64_t> reference_tokens;
    std::vector<std::vector<float>> reference_frames;
    for (std::int64_t token = 1; token <= 12; ++token) {
        const ple_head_ids expected_ids =
                reference_next_ids(metadata, &reference_tokens, token);
        const std::vector<float> frame{static_cast<float>(token)};
        const std::vector<float> expected_window =
                reference_conv_window(reference_frames, frame);
        reference_frames.push_back(frame);

        ple_head_ids actual_ids{};
        std::array<float, kPleConvKernelSize * kChannels> actual_window{};
        ok = ok && expect_ok(state.begin_transaction(),
                             "ring transaction begin failed");
        ok = ok && expect_ok(state.stage_token(token, &actual_ids),
                             "ring token stage failed");
        ok = ok && expect(actual_ids == expected_ids,
                          "ring session hash differs from reference");
        ok = ok && expect_ok(
                state.stage_conv_frame(frame.data(), frame.size(),
                                       actual_window.data(), actual_window.size()),
                "ring conv stage failed");
        ok = ok && expect(std::equal(actual_window.begin(), actual_window.end(),
                                     expected_window.begin()),
                          "committed ring conv window differs from reference");
        ok = ok && expect_ok(state.commit_prefix(1u),
                             "ring single-step commit failed");
    }

    std::array<float, kPleConvHistory * kChannels> history{};
    ok = ok && expect_ok(
            state.copy_committed_conv_history(history.data(), history.size()),
            "wrapped committed history copy failed");
    constexpr std::array<float, kPleConvHistory> expected_history{
            4.0f, 5.0f, 6.0f, 7.0f, 8.0f,
            9.0f, 10.0f, 11.0f, 12.0f};
    ok = ok && expect(history == expected_history,
                      "committed conv ring did not retain the latest nine frames");
    ok = ok && expect(state.committed_context() ==
                              std::array<std::int64_t, 2>{11, 12},
                      "wrapped token context is incorrect");

    ple_session_state moved(std::move(state));
    ok = ok && expect(!state.configured(),
                      "moved-from PLE session remained configured");
    ok = ok && expect_code(state.begin_transaction(),
                           ple_status_code::invalid_state,
                           "moved-from PLE session remained usable");
    ok = ok && expect(moved.configured() &&
                              moved.committed_tokens() == 12u &&
                              moved.committed_context() ==
                                      std::array<std::int64_t, 2>{11, 12},
                      "PLE move lost committed session state");
    return ok;
}

}  // namespace

int main() {
    bool ok = true;
    ok = test_checkpoint_golden_metadata() && ok;
    ok = test_transactional_ids_eos_and_conv() && ok;
    ok = test_fail_closed_contract() && ok;
    ok = test_committed_ring_wrap_and_move() && ok;
    if (!ok) return 1;
    std::puts("qwen4exp-ple-test: pass");
    return 0;
}
